# Generated by Django 5.0.3 on 2024-04-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cleaner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cleaning_material',
            name='image',
            field=models.ImageField(upload_to='Cleaner/cleaning_materials/'),
        ),
    ]
