# Generated by Django 5.0.3 on 2024-04-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cleaner', '0002_remove_stock_quantity_alter_cleaning_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_material',
            name='image',
            field=models.ImageField(upload_to='cleaning_materials/'),
        ),
    ]
