# Generated by Django 5.0.3 on 2024-04-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cleaner', '0003_alter_cleaning_material_image'),
        ('Reception', '0008_alter_room_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('missing_objects', models.TextField(blank=True)),
                ('need_towels', models.IntegerField(default=0)),
                ('additional_comments', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.room')),
            ],
        ),
    ]
