# Generated by Django 5.0.3 on 2024-04-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cleaner', '0004_cleanedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanedroom',
            name='is_cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
