# Generated by Django 5.0.3 on 2024-04-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cleaner', '0005_cleanedroom_is_cleaned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning_material',
            name='description',
        ),
    ]
