# Generated by Django 5.0.3 on 2024-04-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cleaner', '0006_remove_cleaning_material_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cleaning_Material',
            new_name='CleaningMaterial',
        ),
    ]
