name: User Story
description: A User story for the JointProject to outline new features or improvements from the User's perspective.
body:
  - type: markdown
    attributes:
      value: |
        A good user story should be "INVEST" (Independent, Negotiable, Valuable, Estimable, Small, Testable). Please provide as much detail as possible to help us understand the context and the value of this story.

  - type: input
    id: user_story_title
    attributes:
      label: User Story Title
      description: Brief title summarizing the User story.
      placeholder: "As a [role], I want [feature], so that [benefit]."
    validations:
      required: true

  - type: textarea
    id: user_story_description
    attributes:
      label: Detailed Description
      description: Detailed description of the User story, including acceptance criteria.
      placeholder: "Provide a detailed description, including any acceptance criteria or specific requirements."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure to link this task to the appropriate milestone and project to ensure proper tracking and visibility in the project management process.
