name: User Story
description: A new User Story to be implemented.
body:
  - type: input
    id: user_story_title
    attributes:
      label: User Story brief description
      description: Brief title summarizing the User story.
      placeholder: "As a [role], I want [feature], so that [benefit]."
    validations:
      required: true

  - type: textarea
    id: user_story_description
    attributes:
      label: Detailed Description
      description: Detailed description of the User story.
    validations:
      required: true

  - type: input
    id: user_role
    attributes:
      label: Role
      description: Role involved in the user story.
      placeholder: "Enter the role related to this user story."
    validations:
      required: true

  - type: input
    id: sprint_number
    attributes:
      label: Sprint Number
      description: Number of the sprint this user story is part of.
      placeholder: "Enter the sprint number."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure to link this task to the appropriate milestone and project to ensure proper tracking and visibility in the project management process.
        
        > [!NOTE]
        > Role: ${{ inputs.user_role.value }}
        
        > [!IMPORTANT]
        > Sprint: ${{ inputs.sprint_number.value }}
