name: Subtask creation
description: Subtask of a story requested by the product owner for the JointProject.
body:
  - type: markdown
    attributes:
      value: |
        Please, fill out this form to help us track the progress of the JointProject more effectively. Your contribution is highly appreciated!

  - type: textarea
    id: parent_task
    attributes:
      label: Parent task
      description: "Provide the issue number of the parent task. Format your input in Markdown to link directly to the parent task, for example, typing `#4` will link to issue #4. Make sure to verify the issue number before submitting."
      placeholder: "Type the parent task link in Markdown format, e.g., `#4`."
    validations:
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: Task description
      description: Detailed description of the task.
      placeholder: "Describe what needs to be done, any relevant details, and expected outcomes."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure to link this task to the appropriate parent task and milestone to ensure proper tracking and visibility in the project management process.
