import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("http://localhost:8000/accounts/login/?next=/")
    page.get_by_label("Password").click()
    page.get_by_label("Password").fill("admin")
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("link", name="RESTAURANT - Home").click()
    page.get_by_role("button", name="Crear nova reserva").click()
    page.locator("#id_day").fill("2024-09-19")
    page.locator("#id_service").select_option("Dinar")
    page.locator("#id_num_guests").select_option("5")
    page.get_by_role("button", name="Continua").click()
    page.get_by_role("button", name="Client Extern").click()
    page.locator("#id_first_name").click()
    page.locator("#id_first_name").press("CapsLock")
    page.locator("#id_first_name").fill("Client test name")
    page.locator("#id_first_name").press("Tab")
    page.locator("#id_last_name").press("CapsLock")
    page.locator("#id_last_name").fill("Surname test")
    page.locator("#id_last_name").press("Tab")
    page.locator("#id_email").fill("testimport re from playwright.sync_api import Playwright, sync_playwright, expect   def run(playwright: Playwright) -> None:     browser = playwright.chromium.launch(headless=False)     context = browser.new_context()     page = context.new_page()     page.goto(\"http://localhost:8000/accounts/login/?next=/\")     page.g")
    page.locator("#id_email").press("Meta+z")
    page.locator("#id_email").fill("test@asdsad.com")
    page.locator("#id_email").press("Tab")
    page.locator("#id_phone_number").fill("1122334")
    page.get_by_role("button", name="Crear Reserva").click()
    page.locator("#id_phone_number").click()
    page.locator("#id_phone_number").fill("11223345")
    page.get_by_role("button", name="Crear Reserva").click()
    page.locator("#id_phone_number").click()
    page.locator("#id_phone_number").fill("112233456")
    page.get_by_role("button", name="Crear Reserva").click()
    page.get_by_role("button", name="Consultar estat reserves").click()
    page.locator("div:nth-child(7) > .list-extra > #checkbox-icon > form > label > img").first.click()
    page.locator("ul:nth-child(2) > div:nth-child(10) > .list-extra > #checkbox-icon > form > label > img").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("div:nth-child(7) > .list-extra > div:nth-child(2) > form > button").first.click()
    page.locator("div:nth-child(13) > .list-extra > #checkbox-icon > form > label > img").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("div:nth-child(12) > .list-extra > div:nth-child(2) > form > button").click()
