import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("http://localhost:8000/accounts/login/?next=/")
    page.get_by_label("Password").click()
    page.get_by_label("Password").fill("admin")
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("link", name="RESTAURANT - Home").click()
    page.locator("#access-process-buttons").get_by_role("button", name="Nova reserva").click()
    page.locator("#id_day").fill("2024-07-18")
    page.locator("#id_num_guests").select_option("Dinar")
    page.get_by_role("button", name="Client Extern").click()
    page.locator("#id_first_name").click()
    page.locator("#id_first_name").press("CapsLock")
    page.locator("#id_first_name").fill("P")
    page.locator("#id_first_name").press("CapsLock")
    page.locator("#id_first_name").fill("Pepito")
    page.locator("#id_first_name").press("Tab")
    page.locator("#id_last_name").press("CapsLock")
    page.locator("#id_last_name").fill("P")
    page.locator("#id_last_name").press("CapsLock")
    page.locator("#id_last_name").fill("Pepiton")
    page.locator("#id_last_name").press("Tab")
    page.locator("#id_email").fill("pepito03@pepitolandia.com")
    page.locator("#id_phone_number").click()
    page.locator("#id_phone_number").fill("682432738")
    page.get_by_role("button", name="Confirma").click()
    page.locator("#access-process-buttons").get_by_role("button", name="Reserves").click()
