# Generated by Django 5.0.3 on 2024-04-03 13:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reservation', models.CharField(max_length=5)),
                ('dni', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='HotelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=9)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clean', models.BooleanField()),
                ('is_taken', models.BooleanField()),
                ('room_num', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('room_type', models.CharField(choices=[('No seleccionat', 'No seleccionat'), ('Individual', 'Individual'), ('Double', 'Double'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe')], default='Double', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('hoteluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_hosted', models.BooleanField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Reception.hoteluser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('hoteluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Reception.hoteluser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateField()),
                ('exit', models.DateField()),
                ('pension_type', models.CharField(choices=[('Sense pensió', 'Sense pensió'), ('Esmorzar Buffet', 'Esmorzar Buffet'), ('Completa', 'Completa')], default='Sense pensió', max_length=15)),
                ('num_guests', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.room')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.client')),
            ],
            options={
                'unique_together': {('room', 'entry', 'exit')},
            },
        ),
        migrations.CreateModel(
            name='ExtraCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_costs_type', models.CharField(choices=[('Minibar', 'Minibar'), ('Desperfectes', 'Desperfectes'), ('Servei habitacions', 'Servei habitacions'), ('Parking', 'Parking'), ('Perdua de claus', 'Perdua de claus')], max_length=100)),
                ('extra_costs_price', models.IntegerField()),
                ('room_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation')),
            ],
        ),
        migrations.CreateModel(
            name='Despeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_costs', models.IntegerField()),
                ('room_type_costs', models.IntegerField()),
                ('room_reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation')),
            ],
        ),
    ]
