# Generated by Django 5.0.3 on 2024-03-22 16:26

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'User', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'User', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='worker',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='User',
        ),
        migrations.RemoveField(
            model_name='room',
            name='client',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='User',
        ),
        migrations.AddField(
            model_name='client',
            name='hoteluser_ptr',
            field=models.OneToOneField(auto_created=True, default=6, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='hoteluser_ptr',
            field=models.OneToOneField(auto_created=True, default=7, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
