# Generated by Django 5.0.3 on 2024-04-03 18:26

import Reception.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='dni',
        ),
        migrations.AddField(
            model_name='checkin',
            name='id_number',
            field=models.CharField(db_default='12345678A', max_length=20),
        ),
        migrations.AlterField(
            model_name='extracosts',
            name='extra_costs_type',
            field=models.CharField(choices=Reception.config.Config.get_room_extra_costs, max_length=100),
        ),
    ]
