# Generated by Django 5.0.3 on 2024-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_alter_client_options_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='id_number',
            field=models.CharField(default='00000000A', max_length=20),
        ),
        migrations.AddField(
            model_name='hoteluser',
            name='id_type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
