# Generated by Django 5.0.3 on 2024-04-03 19:09

import Reception.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_remove_checkin_dni_checkin_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='num_reservation',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='extracosts',
            name='extra_costs_type',
            field=models.CharField(choices=Reception.config.Config.get_room_extra_costs, max_length=120),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=Reception.config.Config.get_room_types, default='Double', max_length=15),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='pension_type',
            field=models.CharField(choices=Reception.config.Config.get_pension_types, default='Sense pensió', max_length=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='schedule',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='worker',
            name='type',
            field=models.CharField(max_length=120),
        ),
    ]
