# Generated by Django 5.0.3 on 2024-03-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_alter_client_options_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reservation', models.CharField(max_length=5)),
                ('dni', models.CharField(max_length=9)),
            ],
        ),
    ]
