# Generated by Django 5.0.3 on 2024-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_alter_client_options_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
