# Generated by Django 5.0.3 on 2024-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_alter_client_options_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Double', 'Double'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe')], default='Double', max_length=10),
        ),
    ]
