# Generated by Django 5.0.3 on 2024-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0003_alter_checkin_num_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despeses',
            name='pension_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='despeses',
            name='room_type_costs',
            field=models.IntegerField(default=0),
        ),
    ]
