# Generated by Django 5.0.3 on 2024-03-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0003_hoteluser_id_number_hoteluser_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteluser',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='hoteluser',
            name='id_type',
        ),
    ]
