# Generated by Django 5.0.3 on 2024-04-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0004_alter_despeses_pension_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
