# Generated by Django 5.0.3 on 2024-03-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0004_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='check_in',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='roomreservation',
            old_name='check_out',
            new_name='exit',
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('room', 'entry', 'exit')},
        ),
    ]
