# Generated by Django 5.0.3 on 2024-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0005_roomreservation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='check_in_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='check_out_active',
            field=models.BooleanField(default=False),
        ),
    ]
