# Generated by Django 5.0.3 on 2024-03-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0004_remove_hoteluser_dni'),
        ('Reception', '0005_rename_check_in_roomreservation_entry_and_more'),
    ]

    operations = [
    ]
