# Generated by Django 5.0.3 on 2024-03-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0003_checkin'),
        ('Reception', '0006_merge_20240327_1720'),
    ]

    operations = [
    ]
