# Generated by Django 5.0.3 on 2024-04-17 07:52

import Reception.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0006_roomreservation_check_in_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(choices=Reception.config.Config.get_room_prices_per_type, default=100),
        ),
    ]
