# Generated by Django 5.0.3 on 2024-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0007_alter_room_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(default=0),
        ),
    ]
