# Generated by Django 5.0.3 on 2024-03-30 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0007_merge_0003_checkin_0006_merge_20240327_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Reception.client'),
        ),
    ]
