# Generated by Django 5.0.3 on 2024-03-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0008_roomreservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='client',
        ),
    ]
