# Generated by Django 5.0.3 on 2024-05-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0008_alter_room_room_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
