# Generated by Django 5.0.3 on 2024-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0009_delete_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_num',
            field=models.IntegerField(unique=True),
        ),
    ]
