# Generated by Django 5.0.3 on 2024-03-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0009_alter_hoteluser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.client'),
        ),
    ]
