# Generated by Django 5.0.3 on 2024-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0010_alter_room_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
