# Generated by Django 5.0.3 on 2024-04-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0011_alter_client_options_alter_hoteluser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_costs', models.IntegerField()),
                ('room_type_costs', models.IntegerField()),
                ('extra_costs_type', models.CharField(blank=True, choices=[('Minibar', 'Minibar'), ('Desperfectes', 'Desperfectes'), ('Servei habitacions', 'Servei habitacions'), ('Pàrking', 'Parking'), ('Pèrdua de claus', 'Pèrdua de claus')], max_length=100)),
                ('extra_costs_price', models.IntegerField()),
                ('room_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation')),
            ],
        ),
    ]
