# Generated by Django 5.0.3 on 2024-04-03 09:04

import Reception.config
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0011_alter_client_options_alter_hoteluser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_costs', models.JSONField(blank=True, default=Reception.config.Config.get_room_extra_costs)),
                ('extra_costs', models.JSONField(blank=True, default=Reception.config.Config.get_room_type_costs)),
                ('room_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation')),
            ],
        ),
    ]
