# Generated by Django 5.0.3 on 2024-05-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0011_alter_hoteluser_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='schedule',
        ),
    ]
