# Generated by Django 5.0.3 on 2024-04-03 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0012_despeses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despeses',
            name='extra_costs_price',
        ),
        migrations.RemoveField(
            model_name='despeses',
            name='extra_costs_type',
        ),
        migrations.CreateModel(
            name='ExtraCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_costs_type', models.CharField(choices=[('Minibar', 'Minibar'), ('Desperfectes', 'Desperfectes'), ('Servei habitacions', 'Servei habitacions'), ('Pàrking', 'Parking'), ('Pèrdua de claus', 'Pèrdua de claus')], max_length=100)),
                ('extra_costs_price', models.IntegerField()),
                ('room_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation')),
            ],
        ),
    ]
