# Generated by Django 5.0.3 on 2024-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0013_remove_despeses_extra_costs_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracosts',
            name='extra_costs_type',
            field=models.CharField(choices=[('Minibar', 'Minibar'), ('Desperfectes', 'Desperfectes'), ('Servei habitacions', 'Servei habitacions'), ('Parking', 'Parking'), ('Perdua de claus', 'Perdua de claus')], max_length=100),
        ),
    ]
