# Generated by Django 5.0.3 on 2024-04-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0014_alter_extracosts_extra_costs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despeses',
            name='room_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation', unique=True),
        ),
    ]
