# Generated by Django 5.0.3 on 2024-04-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0015_alter_despeses_room_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despeses',
            name='room_reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation'),
        ),
    ]
