# Generated by Django 5.0.3 on 2024-04-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_externalrestaurantclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreservation',
            name='external_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.externalrestaurantclient'),
        ),
    ]
