# Generated by Django 5.0.3 on 2024-04-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_alter_restaurantreservation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalrestaurantclient',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
