# Generated by Django 5.0.3 on 2024-05-07 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_restaurantreservation_client_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreservation',
            name='num_guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
