name: Deploy to Fly.io

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Import secrets
        run: flyctl secrets import -a jointproject < .env
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy -a jointproject
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Dump and load database
        run: |
          python manage.py dumpdata > datadump.json
          fly ssh console -C "python manage.py loaddata datadump.json" -a jointproject
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
